import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import { SessionProvider } from "next-auth/react"
import { auth } from "@/config/auth";
import dbConnect from "@/lib/connectDB";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  await dbConnect();
  return (
    <SessionProvider session={session}>
    <html lang="en">
      <CssBaseline/>
      <body className="bg-white !important">{children}</body>
    </html>
    </SessionProvider>
  );
}
